name = "miner-banner"
main = "src/index.js"
compatibility_date = "2023-03-08"

kv_namespaces = [
    { binding = "mcmodTextures", id = "c27df8d59d3246e88f7cb582830604d8", preview_id = "b42479b02564478692b793b1b12b8a95" }
]
