// noinspection SpellCheckingInspection,JSUnresolvedVariable

function htmlEncode(s)
{
    let ret = ''
    for (let char of s)
    {
        const code = char.codePointAt(0)
        ret += code > 127 ? '&#' + code + ';' : char
    }
    return ret
}
function colorEncode(raw)
{
    if(raw == null) return null

    const len = raw.length
    let indexStart
    if(len === 3 || len === 6) indexStart = 0
    else if(len === 4 || len === 7) indexStart = 1
    else return null

    if(indexStart === 1 && raw.charAt(0) !== '#') return null

    for(let index = indexStart; index < len; index++)
    {
        const char = raw.charAt(index)
        if((char >= '0' && char <= '9') ||
            (char >= 'a' && char <= 'z') ||
            (char >= 'A' && char <= 'Z')
        ) continue
        return null
    }

    return indexStart === 1 ? raw : '#' + raw
}
function fontEncode(raw)
{
    if(raw == null) return null

    for(let char of raw)
    {
        if(char === ' ' || char === '-' || char === '_' || char === ',' ||
            (char >= 'a' && char <= 'z') ||
            (char >= 'A' && char <= 'Z') ||
            (char >= '0' && char <= '9')
        ) continue
        return null
    }

    return raw
}
async function getTexture(rid)
{
    const rGroup = parseInt('' + (parseInt(rid) / 10000))
    const res = await fetch(`https://i.mcmod.cn/item/icon/128x128/${rGroup}/${rid}.png?v=9`, { method: 'get' })
    if(!res.ok) throw await res.text()
    const resBlob = await res.blob()
    const resBuffer = await resBlob.arrayBuffer()
    const resString = String.fromCharCode(...new Uint8Array(resBuffer))
    return btoa(resString)
}
async function resolveSvgAchievement(request, url, env)
{
    const params = url.searchParams
    const rid = params.get('rid')
    const title = params.get('t')
    const subtitle = params.get('st')

    let resB64 = null
    if(rid != null)
    {
        if(env.mcmodTextures && env.mcmodTextures.get && env.mcmodTextures.put)
        {
            const cacheKey = 'item-' + rid
            const cache = await env.mcmodTextures.get(cacheKey, { type: "text" })
            if(cache === null)
            {
                try
                {
                    resB64 = await getTexture(rid)
                    await env.mcmodTextures.put(cacheKey, resB64, {expirationTtl: 3600 * 24 * 30})
                }
                catch (ignored) { }
            }
            else resB64 = cache
        }
        else
        {
            try
            {
                resB64 = await getTexture(rid)
            }
            catch (ignored) { }
        }
    }

    let partImage
    if(resB64 !== null) partImage = `<image xlink:href="data:image/png;base64,${resB64}" x="16" y="16" width="32" height="32"/>`
    else partImage = ''

    let partTitle
    if(title != null)
    {
        const colorTitle = colorEncode(params.get('tc')) ?? '#fafa00'
        const fontTitle = fontEncode(params.get('tf')) ?? 'Microsoft Yahei, Minecraft'
        partTitle = `<text fill="${colorTitle}" font-size="16" font-family="${fontTitle}" x="60" y="26">${htmlEncode(title)}</text>`
    }
    else
    {
        partTitle = ''
    }

    let partSubtitle
    if(subtitle != null)
    {
        const colorSubtitle = colorEncode(params.get('stc')) ?? '#fefefe'
        const fontSubtitle = fontEncode(params.get('stf')) ?? 'Microsoft Yahei, Minecraft'
        partSubtitle = `<text fill="${colorSubtitle}" font-size="16" font-family="${fontSubtitle}" x="60" y="48" >${htmlEncode(subtitle)}</text>`
    }
    else
    {
        partSubtitle = ''
    }

    return new Response(
        `<?xml version="1.0" encoding="UTF-8" ?>
<svg width="320" height="64" viewBox="0 0 320 64" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
<title>${title}</title>
<desc>${subtitle}</desc>
<!-- generated by Miner Banner v${env.RunningVersion} -->
<style>text { user-select: none } image { image-rendering: optimizeSpeed; image-rendering: pixelated; }</style>
<defs>
<g id="h">
    <image width="305" height="8" x="7.5" y="0" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAAICAQAAACSE13KAAAAHklEQVQI1wXBAQEAMAjAIFwTM71/ Fg/moqcRYa/zASLlA4A/5vbyAAAAAElFTkSuQmCC "/>
</g>
<g id="v">
    <image width="8" height="49" x="0" y="7.5" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAABCAQAAABJCSfIAAAAGUlEQVQI12Nk+M/AEMzAzPCXgZHh HMM/BgAgNwQhtB+BKwAAAABJRU5ErkJggg== "/>
</g>
<g id="c">
    <image width="8" height="8" x="0" y="0" preserveAspectRatio="none" xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAQAAABuBnYAAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAA LiMAAC4jAXilP3YAAABVSURBVAjXTcoxCsJAFADR97NrhCQg2Hghu3j/o6yyIfwUInG6GSbSSST1 zxXlDJdMq2r4hWp3t4vEmOHpplm+R+gePkZvcc3Ny6SZDDa1S7Nm0aXiAF3bFjJ6qKvmAAAAAElF TkSuQmCC "/>
</g>
</defs>
<rect fill="#212121" width="305" height="49" x="7.5" y="7.5"/>
<use xlink:href="#h"/>
<use xlink:href="#h" x="0" y="-64" transform="scale(1,-1)"/>

<use xlink:href="#v"/>
<use xlink:href="#v" x="-320" y="0" transform="scale(-1,1)"/>

<use xlink:href="#c"/>
<use xlink:href="#c" x="0" y="-64" transform="scale(1,-1)"/>
<use xlink:href="#c" x="-320" y="-64" transform="scale(-1)"/>
<use xlink:href="#c" x="-320" y="0" transform="scale(-1,1)"/>

${partImage}
${partTitle}
${partSubtitle}
</svg>
`,
        {
            headers: {
                'Content-Type': 'image/svg+xml',
                'Cache-Control': 'public, max-age=3600',
            },
            status: 200,
        }
    )
}

export default resolveSvgAchievement
